version: "3"

services:
  app:
    container_name: kinfei-portfolio
    image: kinfe-portfolio
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
